version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    environment:
      - APP_NAME=App1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3002:3000"
    environment:
      - APP_NAME=App2

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3003:3000"
    environment:
      - APP_NAME=App3
